#!/bin/bash

echo "=== SAMBA SERVER O'RNATISH ==="
echo ""
echo "Bu skript Samba serverini o'rnatib sozlaydi."
echo "Windows kompyuterdan barcha fayllarga kirish imkoni bo'ladi."
echo ""

# IP manzilni ko'rsatish
echo "Server IP manzillari:"
ip addr show | grep "inet " | grep -v "127.0.0.1" | awk '{print "  - " $2}'
echo ""

echo "O'rnatish uchun quyidagi buyruqlarni ketma-ket bajaring:"
echo ""
echo "1. Samba o'rnatish:"
echo "   sudo apt update"
echo "   sudo apt install -y samba samba-common-bin"
echo ""
echo "2. Original konfiguratsiyani saqlash:"
echo "   sudo cp /etc/samba/smb.conf /etc/samba/smb.conf.backup"
echo ""
echo "3. Yangi konfiguratsiyani nusxalash:"
echo "   sudo cp /home/user/smb.conf.new /etc/samba/smb.conf"
echo ""
echo "4. Samba foydalanuvchi qo'shish (parol so'raydi):"
echo "   sudo smbpasswd -a user"
echo ""
echo "5. Xizmatlarni qayta ishga tushirish:"
echo "   sudo systemctl restart smbd nmbd"
echo "   sudo systemctl enable smbd nmbd"
echo ""
echo "6. Firewall ruxsat berish (agar kerak bo'lsa):"
echo "   sudo ufw allow samba"
echo ""
echo "=== WINDOWS DAN ULANISH ==="
echo ""
echo "Windows Explorer da quyidagini yozing:"
echo "  \\\\SERVER_IP\\UserHome"
echo "  \\\\SERVER_IP\\Project"
echo "  \\\\SERVER_IP\\Data"
echo ""
echo "Masalan: \\\\172.27.64.10\\Project"
echo ""
echo "Login: user"
echo "Parol: (smbpasswd bilan o'rnatilgan parol)"